### ISSUE TITLE
Custom resolver

### ISSUE THREAD

**Issue by subhero24** [mrzmmr/rehype-partials#3]
I would like to resolve relative partial paths to the location of the document instead of the current working directory.
The current options.handle has no information about the location of the file, so I am not able to use that.

Is there a possibility to add a custom resolver option?

**Comment by mrzmmr** [comment]
You can set `options.cwd` to the location of the document you want and then paths will be resolved from that location. `options.handle` is a function whilch takes the path currently being worked on and a callback function. For example the default behavior for `options.handle` is basically the same as doing
```
let options = {
    handle(filePath, callback) {
        // Do something with the location of the file like,
        fs.readFile(filePath, 'utf8', callback)
    }
}
```
Adding a custom resolver option probably wouldn't be too difficult. Hope this helps

**Comment by subhero24** [comment]
Thanks for your reply. What I really want to do is resolve the path relative to the file that specified the partial. Implementing the handler as you describe can only do something with the filepath that is already resolved relative to the cwd.

**Comment by mrzmmr** [comment]
Sorry I don't think i understand, maybe you can give an example? If you have a file at `${__dirname}/src/one/two/two.html`
```html
<div><!-- href='../../index.html' --></div>
```
the path will be resolved to `${__dirname}/index.html`, or you can specify where to look from for example setting `options.cwd = 'src'` would resolve to `${__dirname}/src/index.html`.  Nodes path.resolve is used with `options.cwd`, the file that specified the partial's path dirs, and the value in the href comment.

**Comment by subhero24** [comment]
Ah now I see that it is indeed relative, but not for the main entry point.

If I have a file A which has a partial B and that partial B includes another partial C, the path from A to B is relative to the cwd, but the path from B to C is relative to the file B. This was very confusing. But got it working now. Thanks!

**Comment by mrzmmr** [comment]
Glad you you got it working, I'm going to go ahead and close this.
